### ISSUE TITLE
Sometimes the XMR QR code generated is read as invalid by wallets (multiple tested), which is only fixed by rebooting the app.

### ISSUE THREAD

**Issue by nanostos** [bitrequest/bitrequest.github.io#12] opened 2023-02-23 09:15 UTC
This is in the context of using Bitrequest for an XMR physical point of sale solution.

Amount is still detected accurately by wallet, just not address. Bitrequest was not set to use integrated address in this instance, and **the view key was not added to allow payment detection**. It occurred to me that I should have taken a picture of the QR code for troubleshooting. I know this is not very helpful until I can provide an example, sorry. I will add an update here when the error comes up again.

Steps were:
1. Open request window
2. Customer scans and pays successfully (amount and address correct)
3. App is minimised (iOS tablet)
4. App is opened for next customer, amount amended for new order
5. QR code scanned shows 'invalid address' in multiple wallets tested, but still fills amount correctly
6. App must be rebooted to fix

**Comment by nanostos** [comment] 2023-02-25 03:18
The error came up again when I tried to pay at the cafe. Cashier opened app, which took a second to load up, then tapped the Monero logo. It took another second or two to load the exchange rate and then showed the request window with amount at zero. Cashier entered the fiat amount, which updated the QR code in real time. I scanned, but the wallet showed the address as invalid. I took this picture for troubleshooting:
![image](https://user-images.githubusercontent.com/79636894/221333326-fbeb23b4-386a-4e2c-addc-eed9cec9f18a.png)

**Comment by bitrequest** [comment] 2023-02-25 14:11
Strange, i am not able to reproduce this error unfortunately...
This is the URI: undefined:undefined?tx_amount=0.072435

**Comment by nanostos** [comment] 2023-02-27 04:16
This is definitely the biggest issue of the lot, since it prevents the customer from being able to pay. Is there any way I can give you more information to help solve this?

**Comment by bitrequest** [comment] 2023-02-27 10:59
Should be fixed now!
https://github.com/bitrequest/bitrequest.github.io/commit/c4d9e86c43b1519b04c40d14a6e7487a4201ed0d

**Closed as completed** 2024-06-24 22:08 UTC
